default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  database: <%= ENV['mysql_database'] %>
  encoding: utf8
  password: <%= ENV['mysql_password'] %>
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  timeout: 5000
  username: <%= ENV['mysql_username'] %>
